# Generated by Django 4.0.1 on 2022-01-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IOTdevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=26)),
                ('reading', models.FloatField()),
                ('device_id', models.CharField(max_length=36)),
                ('customer_id', models.CharField(max_length=36)),
            ],
            options={
                'db_table': 'IOTdevice',
            },
        ),
    ]
