# Generated by Django 4.0.1 on 2022-01-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotdevice',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
